services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/TransactionService
    depends_on:
      - db
    networks:
      - transaction_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transaction_network

volumes:
  postgres_data:

networks:
  transaction_network:
    driver: bridge