"""init models

Revision ID: c9b7b9b09646
Revises: 
Create Date: 2025-08-06 22:30:02.401554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b7b9b09646'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    bind = op.get_bind()
    meta = sa.MetaData()
    meta.reflect(bind=bind)

    users_table = sa.Table('users', meta, autoload_with=bind)
    test_user_data = {
        'email': 'test@example.com',
        'password': '$argon2id$v=19$m=65536,t=3,p=4$KWaBvb4nl4iVBUVYulWlbQ$YLdMg9wMioPjRxHsapmUzLvUqlUubfLj+an1YsF6t+k',  # user
        'full_name': 'Test User',
        'is_admin': False,
    }
    stmt = users_table.insert().values(**test_user_data)
    bind.execute(stmt)

    admin_user_data = {
        'email': 'admin@example.com',
        'password': '$argon2id$v=19$m=65536,t=3,p=4$fgp6TEWIvRRPDq3A1rFJmA$KvbbxHJWJWbk/1twYQX+OZUySztLDB2NgXQ1egQt9B8',  # admin
        'full_name': 'Administrator',
        'is_admin': True,
    }
    stmt = users_table.insert().values(**admin_user_data)
    bind.execute(stmt)

    result = bind.execute(sa.select(users_table.c.id)).first()
    if result:
        user_id = result[0]
    else:
        raise Exception("No user created.")
    accounts_table = sa.Table('accounts', meta, autoload_with=bind)
    test_account_data = {'user_id': user_id, 'balance': 0}
    stmt = accounts_table.insert().values(**test_account_data)
    bind.execute(stmt)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
